### ISSUE TITLE
bugly统计出现崩溃问题

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/Toaster#103]
#### 问题描述

* 框架版本【必填】：12.0

* 问题描述【必填】：请输入你对这个问题的描述

* 复现步骤【必填】：只在bugly统计发现

* 是否必现【必填】：否

* 出现问题的手机信息【必填】：OPPO/PFJM10

* 出现问题的安卓版本【必填】：Android 12,level 31

* 问题信息的来源渠道【必填】：bugly统计

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：未复现

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：否

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

* 使用原生的 Toast 是否也会出现该问题【必答】：否

#### 其他

* 提
供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
[日志.txt](https://github.com/getActivity/Toaster/files/10822785/default.txt)

* 提供截图或视频（根据需要提供，此项不强制）
![image](https://user-images.githubusercontent.com/15795966/221145426-1403ad13-d822-4308-a6ab-0ca95e6fcca7.png)

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，请提供以下信息：

1. 这个 Bug 是在前台发生的还是后台发生的，还是都有出现？
2. 提供一下这个问题在出现的设备 TOP 5 信息，可以在 Bugly 此处找到：

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/28616817/221152150-4b992f11-08bf-4155-941e-ff3d8110f8b9.png">

**Comment by fuchengxin** [comment]
activity轨迹来看 应该是前台，一直复现不了，有没可能是因为应用崩溃导致数据丢失呢?
![image](https://user-images.githubusercontent.com/15795966/221453739-1e952774-d096-4dd8-923d-e3bfb214e144.png)

**Comment by getActivity** [comment]
小伙子，辛苦再提供一下这个 Bug 的崩溃次数及影响设备数

**Comment by fuchengxin** [comment]
上图的是最近的，下图是全版本的，不过我看了下版本，之前看错版本了，都是下载lib的版本，刚发的版本还未出现，过一段时间看看统计吧
![image](https://user-images.githubusercontent.com/15795966/221462221-823e44fd-997d-48e7-9f23-edf9e412d6f0.png)

**Comment by getActivity** [comment]
可以的，小伙子，这个 issue 给你保留一个月时间，到时候有问题直接到这里反馈，我会及时处理，一个月后我会过来提醒你，你到时候记得及时回复一下（注意超过一个星期不回复会被关 issue）。

**Comment by fuchengxin** [comment]
![image](https://user-images.githubusercontent.com/15795966/222358855-6e2f99ef-74a6-4592-8b82-92e15ff66add.png)
确定了  使用线上引用也有这个问题，api 'com.github.getActivity:Toaster:12.0'，库里面SystemToast都没有第38行0.0

**Comment by getActivity** [comment]
[Toaster-12.2.aar.zip](https://github.com/getActivity/Toaster/files/10871544/Toaster-12.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，我尝试修复了该问题，你后面上线的时候用这个包再试一下，如果后面还有出现请告诉我。

**Comment by getActivity** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/28616817/223113933-7070d0fc-e485-48aa-ba9e-f7c9b6e0a3ed.png">

**Comment by getActivity** [comment]
小伙子，上线后问题还有出现吗？

**Comment by fuchengxin** [comment]
![image](https://user-images.githubusercontent.com/15795966/224588732-dfbb6ad2-4863-43b6-b188-1cc0217f53d8.png)
还有，3.2.3是下的12.2.arr

**Comment by getActivity** [comment]
小伙子，你项目的 targetSdkVersion 版本是多少？

**Comment by fuchengxin** [comment]
31

**Comment by getActivity** [comment]
[Toaster-12.2.aar.zip](https://github.com/getActivity/Toaster/files/10953019/Toaster-12.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，我尝试用另外一种方式修复了这个问题，再试一下看看行不行

**Comment by getActivity** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/28616817/226162354-52808898-7fe1-4c0c-a515-3086741443e2.png">

**Comment by getActivity** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/28616817/230696802-cc63d15f-b3aa-43c4-8304-f6d941747fcd.png">
