### ISSUE TITLE
google官方在Android 12 及更高版本并且必须在文本旁边显示应用图标

### ISSUE THREAD

**Issue by zzb-zzb** [getActivity/Toaster#104]
框架版本【必填】：12.0

问题描述【必填】：请问关于，google官方在Android 12 及更高版本并且必须在文本旁边显示应用图标，这个在12.0版本的适配有吗

复现步骤【必填】：在Android 12 及更高版本并且必须在文本旁边显示应用图标

是否必现【必填】：是

出现问题的手机信息【必填】：小米系列手机

出现问题的安卓版本【必填】：Android 12,level 31

问题信息的来源渠道【必填】：小米手机测试

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题

**Comment by zzb-zzb** [comment]
哪里模板不对
