### ISSUE TITLE
Toaster是否适配了官方在Android 12 及更高版本并且必须在文本旁边显示应用图标

### ISSUE THREAD

**Issue by zzb-zzb** [getActivity/Toaster#105]
#### 问题描述

* 框架版本【必填】：12.0
* 问题描述【必填】：现在Google官方要求，在Android 12 及更高版本并且必须在文本旁边显示应用图标,

* 复现步骤【必填】：在android12的小米手机上。在mainActivity主页面使用Toaster.showShort("Toaster");文本旁边没有显示应用图标。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：android12 的全部手机

* 出现问题的安卓版本【必填】： Android 12，api 31

* 问题信息的来源渠道【必填】：自己在android12的小米手机上集成Toaster看到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档但还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

* 使用原生的 Toast 是否也会出现该问题【必答】：否

#### 其他

* 提供报错堆栈 无

* 提供截图或视频 无

* 提供解决方案 无

**Comment by getActivity** [comment]
小伙子，劳烦提供一下 Google 要求高版本的 Android 上的 Toast 旁边显示应用图标信息的截图或者链接。

**Comment by zzb-zzb** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月7日(周二) 晚上10:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/Toaster] Toaster是否适配了官方在Android 12 及更高版本并且必须在文本旁边显示应用图标 (Issue #105)




 
小伙子，劳烦提供一下 Google 要求高版本的 Android 上的 Toast 旁边显示应用图标信息的截图或者链接。

**Comment by getActivity** [comment]
[消息框概览  |  Android 开发者  |  Android Developers](https://developer.android.google.cn/guide/topics/ui/notifiers/toasts?hl=zh-cn)

**Comment by getActivity** [comment]
小伙子，你发的这个是 Toast API 官方文档，虽然官方文档这样写，但是 Toast 不带应用图标应该也是不影响上架 GooglePlay 吧？

**Comment by zzb-zzb** [comment]
目前上架还没有见有啥影响。还有一个问题，怎么设置toast的宽度，找不到设置的api

**Comment by zzb-zzb** [comment]
请问在哪里修改toast的宽度呢

**Comment by zzb-zzb** [comment]
我想设置toast的宽度怎么设置，有设置接口吗

**Comment by getActivity** [comment]
@zzb-zzb Toast 本身是不支持设置自定义宽高的，宽高默认都是 `wrap_content`，你可以在 Toast 布局最外层套一层 FrameLayout 就可以了，示例代码如下：

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/shape_gradient"
    android:gravity="center"
    android:orientation="horizontal"
    android:padding="10dp">

    <TextView
        android:id="@android:id/message"
        android:layout_width="100dp"
        android:layout_height="wrap_content"
        android:layout_margin="10dp"
        android:textColor="#FFFFFFFF"
        android:textSize="14sp" />
</LinearLayout>
```

**Comment by zzb-zzb** [comment]
![image](https://user-images.githubusercontent.com/18201240/225577345-305833b8-98e1-442d-83b5-01693d40b563.png)

**Comment by zzb-zzb** [comment]
![image](https://user-images.githubusercontent.com/18201240/225577820-0cb8ca32-0ed0-4801-a5bd-f220ebc188ac.png)
这个是我的代码，都没有布局文件，你上面的案例不知道怎么弄

**Comment by zzb-zzb** [comment]
在哪里自定义布局，有参考样式吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [getActivity/Toaster] Toaster是否适配了官方在Android 12 及更高版本并且必须在文本旁边显示应用图标 (Issue #105)




 
@zzb-zzb 小伙子，那这个就需要你自定义布局了

**Comment by getActivity** [comment]
框架文档写了，你回去看一下文档

**Comment by zzb-zzb** [comment]
大神，这句看得不太理解呀
![image](https://user-images.githubusercontent.com/18201240/226263189-887cad78-6b9f-491b-aba9-ad2dd3388c2c.png)

**Comment by getActivity** [comment]
> 大神，这句看得不太理解呀 ![image](https://user-images.githubusercontent.com/18201240/226263189-887cad78-6b9f-491b-aba9-ad2dd3388c2c.png)

小伙子，这句话我已经把东西嚼碎喂你了，你要是看不懂我也没有办法

**Comment by getActivity** [comment]
> 你能不能开放一个函数出来控制toaster距离左右的间距，这样用户体验会更方便更友好

小伙子，你自己尝试实现一遍这样的功能，就能明白为什么框架没有实现了

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
