### ISSUE TITLE
Demo的toast显示时有样式，但我的项目中调用时没有样式

### ISSUE THREAD

**Issue by spyatsea** [getActivity/Toaster#109]
#### 问题描述

* 问题描述【必填】：我运行Demo中显示简单toast的方法Toaster.show(text)时，提示中有样式，toast中底色是蓝色，还会带有APP图标。但当我集成到自己的APP中，运行show方法时，显示的toast是黑色背景，也没有APP图标。请问是什么原因？谢谢。

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】：没有

* 框架文档是否有提及到此问题？【必答】：没有

**Comment by getActivity** [comment]
小伙子，你下载 Demo 工程，把 `MainActivity` 这个类的代码看一遍，应该可以解决你的疑惑。

**Comment by spyatsea** [comment]
我又看了一遍，找到原因了。原来默认是黑色背景，更改了全局的Toast布局（Toaster.setView）后，再show就变成自定义的layout了。
