### ISSUE TITLE
华为鸿蒙3.0系统手机上，项目targetSdkVersion<=29时，后台弹窗不生效,无论悬浮窗开启与否

### ISSUE THREAD

**Issue by hply** [getActivity/Toaster#111]
### 框架版本【必填】

12.3

### 问题描述【必填】

华为鸿蒙系统手机上，项目targetSdkVersion<=29时，后台弹窗不生效；与#98不同，无论悬浮窗开启与否都有这个问题；
demo地址：
cowtransfer.com 口令 e12hze；
或：
https://github.com/hply/TestToaster.git

### 复现步骤【必填】

创建空白项目；app.gradle文件中配置版本如下：
targetSdkVersion 29//30及以上没有问题；

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

29及以下

### 出现问题的手机信息【必填】

HUAWEI P40 Pro,HarmonyOS3.0.0

### 出现问题的安卓版本【必填】

Build.VERSION.RELEASE = 12；Build.VERSION.SDK_INT=31

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

华为，亲测miui没有问题

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="357" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/3881020f-c27d-4b86-b0db-3776e4efd217">

<img width="361" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/29333dee-a920-4596-ab3a-5bba2fd2a5f1">

<img width="357" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/cf474a62-39e8-4794-9826-7c44132d63f0">

**Comment by hply** [comment]
我补录了一个视频，就是我那个demo操作的，会出现，但是闪一下就没了：
https://github.com/hply/TestToaster/blob/main/IMG_2038.mp4

**Comment by getActivity** [comment]
小伙子，我看了你的视频，我现在有一个问题，你现在在权限设置页有这个问题，如果是其他页面有这个问题吗？比如桌面，QQ，微信等，在这些应用上面弹会出现这个问题么？

**Comment by hply** [comment]
> 小伙子，我看了你的视频，我现在有一个问题，你现在在权限设置页有这个问题，如果是其他页面有这个问题吗？比如桌面，QQ，微信等，在这些应用上面弹会出现这个问题吗？

试了下：targetSdk < 30的时候，如果开启了悬浮窗，回桌面和微信、QQ的唤起可以吐司；但是微信是双开的，选择双开微信的那个底部弹窗页面不行，包括唤起的系统分享ACTION_SEND的那个弹层，系统设置等很多系统页面都不行；

此外，即便targetSdk >= 30，如果把悬浮窗打开了，反而不能出现系统的默认吐司,关闭app的悬浮窗权限后如Toaster描述的可以在上面说的targetSdk < 30的全部页面触发系统默认吐司；

这些补充描述都来源上次反馈的华为鸿蒙3.0;在小米的机子上测试全部OK，以上。

**Comment by getActivity** [comment]
小伙子，说一下我的测试结果，在鸿蒙 3.0 的华为机上面，无论是在 targetSdkVersion >= 30 还是 targetSdkVersion < 30，测试结果都是一样的，如果在没有悬浮窗权限的情况下，无法在回到桌面的时候弹 Toast，如果有悬浮窗权限则可以，另外你说的《系统分享对话框》、《选择双开对话框》、《权限设置页面》确实是显示不了 Toast，我这边也测试过了，无论有没有开启悬浮窗权限，有没有开启后台弹窗权限，都是显示不了的。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
