### ISSUE TITLE
[疑惑]：有个疑问，为啥发布新版本会把老版本给删除掉？

### ISSUE THREAD

**Issue by ChawLoo** [getActivity/Toaster#112]
### 问题描述【必填】

我之前是12.2版本，用的好好的，然后突然提示我12.2找不到了，结果一看已经更新了12.3了，这个机制不知道是jitpack的机制还是可以认为设定的？总觉得不妥

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
