### ISSUE TITLE
[疑惑]：如何在模块而不是app里使用

### ISSUE THREAD

**Issue by liuxunfu** [getActivity/Toaster#115]
### 问题描述【必填】

你好，因为我要导出aar包，所以想在模块里使用，而不是在app里使用插件，但是有个问题，必须要初始化吗？初始化时需要传入Application类型参数，但是我只是创建了一个类，无法传入此参数。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你可以开放接口出去外层，让外层来实现，然后来显示 Toast，看看这样是否能解答你的疑惑。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
