### ISSUE TITLE
[建议]：支持深色模式和自定义边距、圆角大小

### ISSUE THREAD

**Issue by fly263** [getActivity/Toaster#116]
### 你觉得框架有什么不足之处？【必答】

1、建议增加一个是否支持深色模式的选项，在深色模式下显示灰色背景
2、建议可以配置Toast的边距和圆角大小，现在只能重写getBackgroundDrawable、getHorizontalPadding、getVerticalPadding这三个方法

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

**Comment by getActivity** [comment]
> 建议增加一个是否支持深色模式的选项，在深色模式下显示灰色背景

这个只能你自己判断了，如果深色模式，初始化的时候设置白色的背景，如果不是则设置黑色的背景，框架目前没有引入 Support 库，没有办法做这个判断，就算做也不值得为了这么个小点引入 Support 库，还用换肤的框架不止 Support 库一套方案，框架没有办法把全部场景兼容到位。

> 建议可以配置Toast的边距和圆角大小，现在只能重写getBackgroundDrawable、getHorizontalPadding、getVerticalPadding这三个方法

小伙子，Toast 边距可以重写 getXOffset 和 getYOffset 方法来解决，而圆角大小属于 View 背景，框架不会干涉，你要是看着圆角大小不顺眼，可以自己重写 getBackgroundDrawable 返回新的 Drawable 对象，框架目前暂时不会考虑开放设置圆角大小的 API 出去，因为这样会让别人误以为这个是 Toast 的背景，但是实际这个是 View 的背景。
