### ISSUE TITLE
[疑惑]：：Toaster 提示Duplicate class，请问是什么原因？

### ISSUE THREAD

**Issue by benxiongbuben** [getActivity/Toaster#117]
### 问题描述【必填】

同时继承了你的[XXPermissions](https://github.com/getActivity/XXPermissions)，但是去掉这个还是会提示以下问题：
提示如下：
Duplicate class com.hjq.toast.ActivityStack found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ActivityToast found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.SafeHandler found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.SafeToast found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.SystemToast found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ToastImpl found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ToastImpl$1 found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ToastImpl$2 found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ToastLogInterceptor found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.ToastStrategy found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.WindowLifecycle found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.config.IToast found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.config.IToastInterceptor found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.config.IToastStrategy found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.config.IToastStyle found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.style.BlackToastStyle found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.style.LocationToastStyle found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)
Duplicate class com.hjq.toast.style.WhiteToastStyle found in modules jetified-ToastUtils-9.6-runtime (com.github.getActivity:ToastUtils:9.6) and jetified-Toaster-12.3-runtime (com.github.getActivity:Toaster:12.3)

Go to the documentation to learn how to Fix dependency resolution errors.

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你的项目是不是依赖了 ToastUtils 库？

**Comment by getActivity** [comment]
框架之前的名字叫 ToastUtils，现在改成了 Toaster，所以你不能同时依赖这两个库。

**Comment by benxiongbuben** [comment]
是的，在[MvvmHelper](https://github.com/hegaojian/MvvmHelper)这个项目框架里，有调用ToastUtils
