### ISSUE TITLE
[建议]:能否在示例中加个动画显示吐司的demo

### ISSUE THREAD

**Issue by wangjianxiang** [getActivity/Toaster#119]
### What are the shortcomings you have noticed in the framework? [Required]

我自己尝试了，将吐司从右边平移滑动显示的动画，但是都失败了。

### Has a similar suggestion been made in the issue list? [Required]

No

### Is the suggestion mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

**Comment by getActivity** [comment]
小伙子，怎么自定义 Toast 动画，框架文档上面不是有写了吗？

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。

**Comment by xusx1024** [comment]
[help](https://github.com/getActivity/Toaster/blob/master/HelpDoc-zh.md#%E6%80%8E%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89-toast-%E6%98%BE%E7%A4%BA%E5%8A%A8%E7%94%BB) 里示例为修改全局动画，如果需要单独定制，示例如下：
```

    /**
     * 竖直方向的Toast
     *
     * @param msg
     */
    private void showVerticalToast(String msg) {
        ToastParams params = new ToastParams();
        params.text = msg;
        params.style = new CustomToastStyle(R.layout.vertical_toast);
        if (mContext instanceof Activity) {
            ToastStrategy strategy = new ToastStrategy() {
                @Override
                public IToast createToast(ToastParams p) {
                    IToast toast = super.createToast(p);
                    CustomToast customToast = ((CustomToast) toast);
                    customToast.setAnimationsId(R.anim.vertical_toast_enter);
                    return customToast;
                }
            };
            strategy.registerStrategy(((Activity) mContext).getApplication());
            params.strategy = strategy;
        }
        Toaster.show(params);
    }
```

**Comment by getActivity** [comment]
@xusx1024 如果你是应用于全局 Toast 动画设置，则可以用框架文档上面写的，但如果你是应用于局部 Toast 动画设置，建议搭配 [EasyWindow](https://github.com/getActivity/EasyWindow) 框架使用会更好一点，Demo 工程中有和这个框架搭配使用的案例。

<img width="1330" alt="Image" src="https://github.com/user-attachments/assets/5cbcf334-65ac-4305-b308-8b24f5f04153" />
