### ISSUE TITLE
[疑惑]：请问作者是通过什么机制实现的toast效果的呢

### ISSUE THREAD

**Issue by mynamecool** [getActivity/Toaster#120]
### 问题描述【必填】

我在做我们APP的自动化的过程中，发现我们APP的toast提示 无法捕捉到，无论是获取页面的xml布局还是监听系统的enqueueToast事件都不无法获取到，后来跟我们公司的安卓开发沟通后得知，使用了您的toast框架。故此前来请教。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
