### ISSUE TITLE
[Question]:

### ISSUE THREAD

**Issue by yangkai69** [getActivity/Toaster#122]
### Question Description [Required]

我试了demo，在android studio自带模拟器（android13或14） 无法实现跨页面显示。
我自己的具体使用场景为：创建账户完成后关闭页面并弹toast提示，然后关闭页面后，该提示也立马消失。
我的需求：关闭页面后toast能继续存在一段时间。
我自己项目的bug：使用WindowManager的方式弹toast，在原生android 13或14会报错，需使用android studio自带模拟器测试，若使用国内手机andorid 13可正常弹，我猜测可能是国内手机产商做了兼容。

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Not Selected

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
