### ISSUE TITLE
[疑惑]：Toast 如何跨页面显示

### ISSUE THREAD

**Issue by yangkai69** [getActivity/Toaster#123]
### 问题描述【必填】

你好，我运行demo的apk，他无法跨页面使用，我的使用场景是：完成了账号注册，提示toast，关闭页面。这时toast会随着页面一起被关闭。
我这种需求，使用咱们框架是否能实现？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你确定这个问题文档上面没有写？

**Comment by yangkai69** [comment]
> 小伙子，你确定这个问题文档上面没有写？

我使用了文档上的方法，但是在android 13/14的系统里显示的不正确。
我需要将toast显示在页面中间，但是在android 13/14系统（android studio自带模拟器）里，他显示在了底部。
ps:我试了下国内系统，是显示正确的。

**Comment by yangkai69** [comment]
我重新提一个吧，我觉得这是个bug

**Comment by getActivity** [comment]
https://github.com/getActivity/Toaster/issues/124
