### ISSUE TITLE
[Question]:Toaster 不支持2个textview的这种展示吗，只能传一个字符串进去 ，想传2个文本字符就不支持了

### ISSUE THREAD

**Issue by DeepDevCoding** [getActivity/Toaster#125]
### Question Description [Required]

Toaster 不支持2个textview的这种展示吗，只能传一个字符串进去 ，想传2个文本字符就不支持了。比如下面截图这种。不支持稍微复杂一点布局文本的设置？？？？

<img width="347" alt="image" src="https://github.com/getActivity/Toaster/assets/37864029/97223865-a7c3-4e55-9b4e-3186a84b4df5">

### Is the issue mentioned in the framework documentation? [Required]

Not Selected

### Did you consult the framework documentation but couldn't find a solution? [Required]

Not Selected

### Has a similar issue been reported in the issue list? [Required]

Not Selected

### Have you searched the issue list but couldn't find a solution? [Required]

Not Selected

**Comment by DeepDevCoding** [comment]
上下两个textview，都要动态设置字符串。怎么解决

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写

**Comment by xuexixuexijpg** [comment]
> 上下两个textview，都要动态设置字符串。怎么解决

最后怎么解决？我看使用CustomToastStyle后拿不到创建的view，不能通过findViewById形式来自己设置布局里的元素

**Comment by xuexixuexijpg** [comment]
> > 上下两个textview，都要动态设置字符串。怎么解决
> 
> 最后怎么解决？我看使用CustomToastStyle后拿不到创建的view，不能通过findViewById形式来自己设置布局里的元素

好吧，要自己实现IToastStyle，在创建view时自己手动设置就行
