### ISSUE TITLE
[疑惑]：文字过长时，会自动换行，能否不自动换行。

### ISSUE THREAD

**Issue by oooo7777777** [getActivity/Toaster#127]
### 问题描述【必填】

你好，文字过长时，会自动换行，能否控制不自动换行

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，Toast 的 View 视图你可以通过实现框架的样式接口来实现，至于你要改成什么样，都是可以实现的，但是有一点是肯定的，框架中默认就是应该要换行的，因为原生的 Toast 都是会自动换行的，并且不换行会导致消息显示不全。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
