### ISSUE TITLE
[Bug]:鸿蒙3.0系统下后台无法显示toast

### ISSUE THREAD

**Issue by aimeryxie** [getActivity/Toaster#128]
### Framework Version [Required]

com.github.getActivity:Toaster:12.6

### Issue Description [Required]

[Bug]:鸿蒙3.0系统下后台无法显示toast

### Steps to Reproduce [Required]

home键后无法显示toast

### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

30

### Device Information [Required]

华为mate20 ，鸿蒙3.0系统

### Android Version [Required]

华为mate20 ，鸿蒙3.0系统

### Issue Source Channel [Required]

Encountered by myself

### Is it specific to certain device models? [Required]

鸿蒙系统3.0

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

No

**Comment by getActivity** [comment]
小伙子，你确定这个问题文档上面没有写？
