### ISSUE TITLE
[建议]：使用建造者模式创建toast

### ISSUE THREAD

**Issue by xuxiaocheng0201** [getActivity/Toaster#129]
### 你觉得框架有什么不足之处？【必答】

一个是 delayShow 和 debugShow 没法选择 Long 还是 Short 模式
另一个是希望可以局部定义 style （就是不修改全局设置，指定一条其他 style 或 strategy的 toast ）

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### 你觉得该怎么去完善会比较好？【非必答】

使用建造者模式创建toast

**Comment by xuxiaocheng0201** [comment]
没找到文档在哪，是README吗？

**Comment by getActivity** [comment]
小伙子，debugShow 目前暂时不支持自定义显示时间，你在这方面是有什么需求吗？
