### ISSUE TITLE
[疑惑]：使用自定义布局的toast不能控制显示时长吗

### ISSUE THREAD

**Issue by ZxGump** [getActivity/Toaster#130]
### 问题描述【必填】

使用自定义布局的toast不能控制显示时长吗

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，你确定这个问题上面文档上面没有写？

**Comment by ZxGump** [comment]
![image](https://github.com/getActivity/Toaster/assets/28387077/2407e92e-7b31-4fb9-90e0-801446acdb26)
就这默认的两种

**Comment by getActivity** [comment]
小伙子，你用 [EasyWindow](https://github.com/getActivity/EasyWindow) 实现这个需求吧。

**Comment by ZxGump** [comment]
ok
