### ISSUE TITLE
[Bug]：三星手机 Galaxy S23 toast未生效

### ISSUE THREAD

**Issue by Edwin-n** [getActivity/Toaster#132]
### 框架版本【必填】

12.6

### 问题描述【必填】

三星手机 Galaxy S23 安卓13 , ActivityStack 类getForegroundActivity()方法获取前台 Activity 对象为null，导致Toaster调用系统toast（ActivityStack implements Application.ActivityLifecycleCallbacks ）

### 复现步骤【必填】

同上

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星手机 Galaxy S23

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

部分

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by getActivity** [comment]
<img width="303" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/cddb4ead-85c1-4df0-adbd-d3009dd7b75b">

<img width="301" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/7f437813-3cb0-4a83-b179-925e03c4ee26">

<img width="301" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/cc37520b-1ba7-4578-aed3-14199343c41d">

<img width="1460" alt="image" src="https://github.com/getActivity/Toaster/assets/28616817/eda79405-0ba9-41aa-a6ac-a5d7f0a04ba7">

**Comment by getActivity** [comment]
小伙子，根据你目前提供的信息，我无法复现到这个问题，请你提供更多的信息辅助我继续排查。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
