### ISSUE TITLE
[Bug]:华为Mate20切换语言不生效？

### ISSUE THREAD

**Issue by AgoniAlways** [getActivity/Toaster#133]
### Framework Version [Required]

com.github.getActivity:Toaster:12.5

### Issue Description [Required]

AppCompatDelegate.setApplicationLocales(LocaleListCompat.forLanguageTags("de"))
修改语言后，语言没有切换过来，自带的Toast会自动切换语言
                    Toast.makeText(this@SettingActivity,R.string.str_change_success,Toast.LENGTH_SHORT).show()
                    Toaster.showShort(R.string.str_change_success)

### Steps to Reproduce [Required]

AppCompatDelegate.setApplicationLocales(LocaleListCompat.forLanguageTags("de"))
修改语言后，语言没有切换过来，自带的Toast会自动切换语言

### Is the Issue Reproducible? [Required]

Yes

### Project targetSdkVersion [Required]

   minSdk 24         targetSdk 33         

### Device Information [Required]

华为Mate20

### Android Version [Required]

鸿蒙OS 3.0.0   Android 10

### Issue Source Channel [Required]

Encountered by myself

### Is it specific to certain device models? [Required]

华为Mate20 鸿蒙OS 3.0.0   Android 10

### Does the latest version of the framework have this issue? [Required]

Yes

### Is the issue mentioned in the framework documentation? [Required]

No

### Did you consult the framework documentation but couldn't find a solution? [Required]

Yes

### Has a similar issue been reported in the issue list? [Required]

No

### Have you searched the issue list but couldn't find a solution? [Required]

Yes

### Can the issue be reproduced with a demo project? [Required]

Yes

### Provide Screenshots or Videos

![Screenshot_20240308_161133_com qxz pollux](https://github.com/getActivity/Toaster/assets/34439879/4c6ca922-9f1a-4fe6-be18-5beea4e717a7)
![微信截图_20240308161447](https://github.com/getActivity/Toaster/assets/34439879/efbd43b4-d3ef-4c70-8150-7cf0e21dc3e1)

**Comment by getActivity** [comment]
小伙子，框架使用的是 Application 的 Resources 对象获取的字符串，你看一下用 Application 获取到字符串是不是也是中文？

**Comment by AgoniAlways** [comment]
![image](https://github.com/getActivity/Toaster/assets/34439879/3a8aecfb-222b-4ce2-8cdc-e89370a58b00)
两种方式貌似都没生效
我换了魅族20 不需要通过Application 方式获取资源，语言自动生效 :(

**Comment by getActivity** [comment]
> ![image](https://private-user-images.githubusercontent.com/34439879/311922462-3a8aecfb-222b-4ce2-8cdc-e89370a58b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTQzOTMsIm5iZiI6MTcxMDIxNDA5MywicGF0aCI6Ii8zNDQzOTg3OS8zMTE5MjI0NjItM2E4YWVjZmItMjIyYi00Y2UyLThjZGMtZTg5MzcwYTU4YjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDAzMjgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjQwZGZlYzUwNmRiNDRkNmZhOTVhNmNkMTZmOWE0ZGJkNTE5NDgxMDBkNzNlMjExOWY5ZjUzMDIzNTUyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0b4dVDhLLov2YA3bcE3-pe-FBxhwAOIlPLwVrYoU_bI) 两种方式貌似都没生效 我换了魅族20 不需要通过Application 方式获取资源，语言自动生效 :(

小伙子，你确定这个回答对应着我的问题？

**Comment by AgoniAlways** [comment]
![image](https://github.com/getActivity/Toaster/assets/34439879/3f898222-48fb-432f-99b7-4a6b84107f1c)
轮子哥，你指的是这样？

**Comment by AgoniAlways** [comment]
![image](https://github.com/getActivity/Toaster/assets/34439879/0b20321f-cbca-4155-8159-403f03cc1aa8)
同样情况下，我换了魅族20，就是正常的

**Comment by getActivity** [comment]
小伙子，你这个问题是语种切换的问题，和 Toast 框架没有关系吧？如果是框架的问题欢迎你反馈给我，如果不是框架的问题需要你自行解决。
