### ISSUE TITLE
[疑惑]：自定义显示时间

### ISSUE THREAD

**Issue by 15281087434** [getActivity/Toaster#134]
### 问题描述【必填】

不能自定义显示时间么

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

    * 看似回答了问题，但是实际回答是乱选的，没有按照问题的要求去核实

    * issue 最后一个问题没有回答，回答不完整

请重新提一个 issue 并纠正以上问题
