### ISSUE TITLE
[疑惑]：请问怎么控制Toast只能在当前界面显示呢

### ISSUE THREAD

**Issue by thbpc** [getActivity/Toaster#135]
### 问题描述【必填】

1，我测试了一下demo，Toast在所有界面都能显示出来，甚至在后台也能显示出来，的确很强大。但是我如果想配置Toast只能在当前界面显示，并且app在后台时不显示，应该如何配置呢

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
重新实现并设置新的 Toast 策略，在 showToast 中判断应用是否处于前台，如果是就显示，反之则亦然。
