### ISSUE TITLE
[疑惑]：怎么修改系统Toast 的显示时长

### ISSUE THREAD

**Issue by xiaoma-cell** [getActivity/Toaster#136]
### 问题描述【必填】

设置Toast的显示时长，在后台Toast无法被设置

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
