### ISSUE TITLE
[Bug]：折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全

### ISSUE THREAD

**Issue by yuer1218** [getActivity/Toaster#138]
### 框架版本【必填】

android

### 问题描述【必填】

[Bug]：折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全，猜测的原因是，切换时application的环境出现变化

### 复现步骤【必填】

折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全，猜测的原因是，切换时application的环境出现变化

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

华为 mate xs2

### 出现问题的安卓版本【必填】

android13

### 是部分机型还是所有机型都会出现【必答】

折叠屏

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by yuer1218** [comment]
添加问题截图
![Screenshot_20240807_172240](https://github.com/user-attachments/assets/f09e6898-c143-4760-868b-4779c597a99c)
![Screenshot_20240807_172258](https://github.com/user-attachments/assets/5a7a43a4-49b0-46d6-90e1-4a34cb156f1c)

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

<img width="835" alt="image" src="https://github.com/user-attachments/assets/2616a4af-922f-4f10-bca0-a57ecf9b41f5">

* 以上选项没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 [issue 模板](https://github.com/getActivity/IssueTemplateGuide)填写

**Comment by MhuiHugh** [comment]
超市收银机Android11，双屏上无法显示加上权限可以显示 <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

**Comment by MhuiHugh** [comment]
超市收银机双屏Android11系统，2个屏幕无法显示加permission.SYSTEM_ALERT_WINDOW  后可显示
