### ISSUE TITLE
[Bug]：折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全

### ISSUE THREAD

**Issue by yuer1218** [getActivity/Toaster#139]
### 框架版本【必填】

12.6

### 问题描述【必填】

折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全

### 复现步骤【必填】

折叠屏全屏进应用，然后切换到半屏，此情况下显示长字串会显示不全

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

华为 mate xs2

### 出现问题的安卓版本【必填】

android13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

折叠屏

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

![Screenshot_20240807_172240](https://github.com/user-attachments/assets/616066d1-62c9-4701-8660-fc70b94efd7c)
![Screenshot_20240807_172258](https://github.com/user-attachments/assets/64f963af-e707-4152-8d20-ba4b6de3eb8c)

**Comment by getActivity** [comment]
小伙子，这个问题我无法复现，因为我没有折叠手机，这个问题需要你先行排查问题的原因，然后将问题的原因反馈给我。

**Comment by yuer1218** [comment]
查下来问题出在折叠屏折叠和展开变换时，宽度不会重新计算，现在解决方法是判断文字是否超过屏幕宽度，如果超过就强制写死宽度
![image](https://github.com/user-attachments/assets/408d62d7-50e8-4409-afba-72d8a68c0758)

**Comment by getActivity** [comment]
小伙子，你确定一下这两个问题：
1. 使用原生的 Toast 是否也会出现
2. 其他品牌的折叠屏是否也会出现

**Comment by yuer1218** [comment]
1.原生toast没有出现这个问题，但是原生的toast有一个问题就是很长的字串会显示省略号，这个也是使用这个库的原因
2.我手边也只有这一台折叠机，其他的折叠机是否有问题不知道

**Comment by getActivity** [comment]
我目前判断的是，这个问题大概率是厂商的问题，要么是华为的，要么是谷歌的，跟框架的关系不大，折叠屏在折叠的时候，简单的 UI 的变化这一动作应该由系统来适配，而不是由应用来适配，但是我目前看到你的情况是，折叠屏在折叠的时候，对 Activity 适配是没有问题的，但是对于 WindowManager 适配是有问题，对于这种问题，我建议你直接反馈给华为官方。
