### ISSUE TITLE
[建议]：将混淆规则直接内置到库内

### ISSUE THREAD

**Issue by Reginer** [getActivity/Toaster#141]
### 你觉得框架有什么不足之处？【必答】

混淆规则粗暴而且比较笼统，实际不需要把库下面的所有类都keep吧。

不确定最小keep哪些文件，可以自己在库中内置一个混淆规则，有更新直接就改了使用的也不关注。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

build.gradle文件中配置 consumerProguardFiles("consumer-rules.pro")，consumer-rules.pro文件中写当前库需要的混淆规则

**Comment by getActivity** [comment]
现在的框架不加混淆规则也是可以正常使用的，但是站在框架作者的角度来讲，是不希望你去混淆框架代码的，无论你出于何种目的。

**Comment by Reginer** [comment]
如果想要保留框架版权信息可以增加一个标识类单独保持一个。
站在使用者的角度来说，开启混淆就为了减小体积，框架提供的那些api也不会全部用到，开启混淆可以将它们删掉，现在这规则加上了框架内没用到的api也都还在。
