### ISSUE TITLE
[Bug]：横屏时，如果字体过大文字过多，会宽度缩短，自动换行，一行显示不了几个字

### ISSUE THREAD

**Issue by ymwm-lxl** [getActivity/Toaster#142]
### 框架版本【必填】

12.6

### 问题描述【必填】

横屏时，如果修改getsize为较大字体（使用了autosize，控制分辨率1920x1080，这里字体设置为30dp），则会自动换行，一行最多只有10个字，显示效果很不好，不知道怎么解决，网上说可以setGravity(Gravity.CENTER or Gravity.FILL_HORIZONTAL , 0, 0)，试了也不行。

### 复现步骤【必填】

初始化时自定义style，
修改文字大小
调用show方法

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

红米note13pro

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
如果是 AutoSize 的问题，请自行联系 AutoSize 作者解决，如果不是 AutoSize 的问题，请将 AutoSize 去掉再进行测试，如果还有问题再反馈给我。

**Comment by Klosw** [comment]
我也遇到这个问题了 关闭 AutoSize  后只显示 一半的屏幕 在哪里显示 设置的 toast 宽度的

**Comment by Klosw** [comment]
> 我也遇到这个问题了 关闭 AutoSize 后只显示 一半的屏幕 在哪里显示 设置的 toast 宽度的

重写 ToastStrategy createToast 使用自己的 CustomToast 然后重写 setText 计算实际宽度 设置死的 宽度 暂时解决问题

**Comment by xiangsss** [comment]
用autosize的话，有没有好的解决方法？

**Comment by getActivity** [comment]
> 用autosize的话，有没有好的解决方法？

AutoSize 已经不维护了，你如果还要坚持用，要做好准备填它的所有坑。

**Comment by Cancrileo** [comment]
/**
 * 锁定密度的 Toaster 样式：
 *
 * 背景：项目使用 AndroidAutoSize 做屏幕适配，横屏页面会通过
 * AutoSize.autoConvertDensity 修改 Application/Activity 的 density，
 * 导致此时 Toaster 默认样式按"被改大的 density"渲染 sp/dp，
 * 横屏 Toast 文字与圆角 Padding 都被同比放大（约 1.78×），观感异常。
 *
 * 方案：在 App 进程刚起来、AutoSize 还没改 density 之前，缓存初始 density/scaledDensity，
 * 之后所有 dp/sp 转换都基于这份"基线 metrics"做线性换算，
 * 不再读取 context.resources.displayMetrics（那个会被 AutoSize 篡改）。
 *
 * 注意：横竖屏切换由 [me.jessyan.autosize.AutoSize] 全局接管，本类只关心 Toast 样式不被 AutoSize 拖累。
 */
class FixedDensityToastStyle(application: Context) : BlackToastStyle() {

    /** 基线 density：进程启动 / Application onCreate 期间的"原始密度"，AutoSize 改不到 */
    private val baseDensity: Float
    private val baseScaledDensity: Float

    init {
        val metrics: DisplayMetrics = application.resources.displayMetrics
        baseDensity = metrics.density
        baseScaledDensity = metrics.scaledDensity
    }

    /** 字号按基线 sp 换算 → 直接得到 px，绕过被 AutoSize 改过的 metrics */
    override fun getTextSize(context: Context): Float {
        return 14f * baseScaledDensity
    }

    override fun getHorizontalPadding(context: Context): Int {
        return (24f * baseDensity).toInt()
    }

    override fun getVerticalPadding(context: Context): Int {
        return (16f * baseDensity).toInt()
    }

    override fun getTranslationZ(context: Context): Float {
        return 3f * baseDensity
    }

    override fun getBackgroundDrawable(context: Context): Drawable {
        // 父类用 dp 算圆角依赖 metrics；这里复刻 10dp 但用 baseDensity，避免横屏圆角被放大
        val drawable = GradientDrawable()
        drawable.setColor(0xB3000000.toInt())
        drawable.cornerRadius = 10f * baseDensity
        return drawable
    }
}


      // 锁定 Toast 密度：避免 AutoSize 横屏修改 density 后 Toast 字体被同比放大
        Toaster.setStyle(FixedDensityToastStyle(this))



解决方案

**Comment by Klosw** [comment]
非常高兴的 跑过去看了一眼代码 ,我是自定义布局 ,发现无从下手    哈哈哈
